import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Own It Social Portal',
  description: 'Generated by Own It Social',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className="font-sans">{children}</body>
      <footer className='flex items-center justify-center w-full h-24 border-t text-emerald-700 font-semibold'>
        <a
          className='flex items-center justify-center'
          href='https://artifactbin.com?utm_source=template-repo&utm_campaign=oss'
          target='_blank'
          rel='noopener noreferrer'
        >
          Deployed by Own It Social
        </a>
      </footer>
    </html>
  );
}
